spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydrive_test?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.zishen.mydrive.model